# build.yml
name: Build Project
description: 'Configure and build via CMake'

inputs:
  cmake_arch:
    required: true
    type: string
  build_type:
    required: true
    type: string
  version:
    required: true
    type: string

runs:
  using: composite
  steps:

    # 
    # ==========================================================================================
    - name: Debug Current Directory
      run: |
        echo "Current directory: $(pwd)"
        echo "Workspace directory: ${GITHUB_WORKSPACE}"
        ls -R
      shell: bash

    # 
    # ==========================================================================================
    - name: Configure CMake
      run: |
        if [ "${{ inputs.version }}" == "Demo" ]; then
          cmake -S "${GITHUB_WORKSPACE}" -B "${GITHUB_WORKSPACE}/build" -DBUILD_DEMO=ON ${{ inputs.cmake_arch }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
        elif [ "${{ inputs.version }}" == "Full" ]; then
          cmake -S "${GITHUB_WORKSPACE}" -B "${GITHUB_WORKSPACE}/build" -DBUILD_DEMO=OFF ${{ inputs.cmake_arch }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
        else
          echo "Unexpected version: ${{ inputs.version }}"
          exit 1
        fi
      shell: bash

    # 
    # ==========================================================================================
    - name: Build
      run: cmake --build "${GITHUB_WORKSPACE}/build" --config ${{ inputs.build_type }}
      shell: bash

    # 
    # ==========================================================================================
    - name: Extract and Set Configuration Variables
      run: |
        echo "Reading configuration from config.cmake..."
        while IFS=' ' read -r key value
        do
          value=$(echo $value | tr -d '"')  # Remove quotes
          echo "$key=$value" >> $GITHUB_ENV
        done < <(grep 'set(w' ${GITHUB_WORKSPACE}/config.cmake | sed -e 's/set(//g' -e 's/)//g' -e 's/\s\+/ /g')
      shell: bash

    # 
    # ==========================================================================================
    - name: Use Variables
      run: |
        echo "Plugin Name: $wPLUGIN_NAME"
        echo "Company Name: $wCOMPANY_NAME"
        echo "Company ID: $wCOMPANY_ID"
        echo "Project Version: $wPROJECT_VERSION"
        echo "Manufacturer Code: $wPLUGIN_MANUFACTURER_CODE"
        echo "Formats: $wFORMATS"
        echo "Is Synth: $wIS_SYNTH"
        echo "Needs MIDI Input: $wNEEDS_MIDI_INPUT"
        echo "Needs MIDI Output: $wNEEDS_MIDI_OUTPUT"
        echo "Plugin Code: $wPLUGIN_CODE"
      shell: bash